namespace NewBegin.Data.Enums
{
    internal enum BusinessType
    {
        Food,
        Health,
        Shop,
        ManicureAndPedicure,
        Massage,
        Hairdressing,
        Psychology,
        Tattoo,
        Sports,
        AutoServices,
        VideoServices,
        Photography,
        Animals, 
        CarriageServices,
        Design,
        CleaningServices,
        ComputerServices,
        Furniture,
        Music,
        Education,
        ClothingAndFootwear,
        LegalServices,
        RepairOfHouseholdAppliances,
        RealtorServices,
        SanitaryEngineering,
        ConstructionAndRepair,
        Dancing,
        Tourism,
        Floristics,
        Electrics
    }
}
